// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>
@protocol NTVCoreApplicationCore;


@protocol NTVCoreApplicationCore

- (nullable id<NTVCoreApplicationCore>)shared;

- (double)multiply:(double)value1
            value2:(double)value2;

- (nonnull NSString *)getVersion;

@end
