// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/core/application_core.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol NTVCoreApplicationCore;

namespace djinni_generated {

class ApplicationCore
{
public:
    using CppType = std::shared_ptr<::ApplicationCore>;
    using CppOptType = std::shared_ptr<::ApplicationCore>;
    using ObjcType = id<NTVCoreApplicationCore>;

    using Boxed = ApplicationCore;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

